name: Terraform Checks

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: env/${{ github.event.inputs.environment }}

    steps:          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set environment input
        run: echo "${{ github.event.inputs.environment }}" > env_relay

      - name: Debug env_relay contents
        run: cat env_relay

      - name: Upload environment artifact
        uses: actions/upload-artifact@v4
        with:
          name: env_relay
          path: env_relay
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug IAM Role ARN
        run: echo "IAM Role ARN is ${{ secrets.IAM_ROLE_ARN }}"

      - name: AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{vars.AWS_REGION }}

      - name: Terraform Format Check
        run: terraform fmt -recursive

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.BACKEND_BUCKET }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}" \
            -backend-config="region=${{ vars.BACKEND_REGION }}"

      - name: Terraform Validate
        run: terraform validate
