name: Check

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: 
      IAM_ROLE_ARN:
        required: true 

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: env/${{ inputs.environment }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug IAM Role ARN
        run: echo "IAM Role ARN is ${{ secrets.IAM_ROLE_ARN }}"

      - name: Debug env
        run: echo "env is ${{ inputs.environment }}"

      - name: Debug aws region
        run: echo "region is ${{ vars.AWS_REGION }}"

      - name: AWS credential
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Format Check
        run: terraform fmt -recursive

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.BACKEND_BUCKET }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}" \
            -backend-config="region=${{ vars.BACKEND_REGION }}"

      - name: Terraform Validate
        run: terraform validate
