name: Master

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  call-checks:
    uses: ./.github/workflows/check.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: 
      IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}
      PUBLIC_KEY: ${{ secrets.ID_RSA_PUBLIC }}
      SSM_DB_ENDPOINT: ${{ secrets.SSM_DB_ENDPOINT }}
      SSM_DB_NAME: ${{ secrets.SSM_DB_NAME }}
      SSM_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SSM_DB_USERNAME: ${{ secrets.DB_USERNAME }}

  call-deploy:
    needs: call-checks
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: 
      IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}
      PUBLIC_KEY: ${{ secrets.ID_RSA_PUBLIC }}
      SSM_DB_ENDPOINT: ${{ secrets.SSM_DB_ENDPOINT }}
      SSM_DB_NAME: ${{ secrets.SSM_DB_NAME }}
      SSM_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SSM_DB_USERNAME: ${{ secrets.DB_USERNAME }}
